### ISSUE TITLE
Feature: Password Hashing

### ISSUE THREAD

**Issue by davidbru** [OpenSouce-LNMIIT/Cybros-Web-Application#114]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Currently the password is stored in plaintext in the database. 

**Expected behaviour:**
Ideally the password is salted and/or peppered and hashed before it is saved in the database. 
This stackoverflow answer is probably a good starting point:
https://stackoverflow.com/a/1581919

Downside: The process of creating the first admin user (as described in the readme) gets more complicated.

**Comment by chaitanyagiri** [comment]
@davidbru  hashing will definately improve security and considering admin creation process yes it will be complex in local machine. It could be done. To add an extra layer of security currently we have session key static we can produce a random alphanumeric string and set it as session key that'd also help.

**Comment by rustagishubhi** [comment]
This issue is resolved so it can be closed.
