### ISSUE TITLE
Parallax scrolling not working in google chrome android.

### ISSUE THREAD

**Issue by chaitanyagiri** [OpenSouce-LNMIIT/Cybros-Web-Application#51]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
![ss](https://user-images.githubusercontent.com/26071627/31561636-2659f2be-b076-11e7-89ab-a6cfbf04195b.jpeg)

**Expected behaviour:**
parallax scrolling must work in mobile devices.

put a 'x' inside [ ] to check.

**Comment by RamanaVem** [comment]
@chaitanyagiri is it working in responsive browser mode? What is the best way to run in mobile?
